const assert=require('node:assert/strict'),fs=require('node:fs'),L=require('../preview/learning.js');
const bank=JSON.parse(fs.readFileSync('assets/data/questions.json')),types=JSON.parse(fs.readFileSync('assets/data/types.json')),coverage=JSON.parse(fs.readFileSync('assets/data/coverage.json'));
const qs=bank.filter(q=>q.sourceId==='file3'&&q.variant==='modified'&&!q.reviewOnly),memory={};
for(const q of qs)L.record(memory,q.id,false,'old',q.id);
assert.equal(L.plan(bank,memory,{review:true,count:10,source:'file3',variant:'modified'}).length,10);
assert.equal(L.pending(memory).length,qs.length,'Unselected mistakes remain saved');
assert.equal(L.plan(bank,memory,{review:true,count:0}).length,0);
assert.equal(L.plan(bank,memory,{count:NaN,source:'file2',variant:'modified'}).length,10);
const trio=qs.slice(0,3).map((q,i)=>({...q,conceptKey:'unique-'+i})),m={};L.record(m,trio[0].id,true,'one',1);L.record(m,trio[0].id,true,'two',2);L.record(m,trio[1].id,true,'one',1);
assert.equal(L.plan(trio,m,{count:1},()=>0)[0].id,trio[2].id,'Unseen before practised or mastered');
const reports=L.sourceProgress(bank,m);assert.equal(reports.length,6);const file3=reports.find(g=>g.source==='file3'&&g.variant==='modified');assert.equal(file3.mastered,1);assert.equal(file3.tried,2);assert.equal(file3.total,80);assert(file3.mastered/file3.total<1);
const q=bank.find(q=>q.type==='choice'&&!q.reviewOnly),map=new Map(bank.map(q=>[q.id,q]));
const draft={id:'draft',ids:[q.id],index:0,exam:true,answers:[],selected:'',revealed:false,hints:0,options:q.options};
assert(L.validSession(draft,map,types));
for(const patch of [{index:-1},{index:2},{ids:[]},{ids:[q.id,q.id]},{options:[]},{answers:[{id:q.id,correct:true}]},{selected:null},{hints:900}])assert(!L.validSession({...draft,...patch},map,types),JSON.stringify(patch));
const complete={...draft,index:1,answers:[{id:q.id,correct:true}]};assert(L.validSession(complete,map,types));
assert(!L.validSession({...complete,answers:[{id:q.id,correct:null}]},map,types),'Only self-graded answers may wait for assessment');
const raw={schema:2,saved:[q.id,q.id,-3],memory:{[q.id]:{wrong:1,streak:0,last:1},bad:null},orders:null,settings:{goal:0,motion:false},attempts:[null,{date:'',answers:[{id:q.id,correct:true},null,{id:4,correct:'yes'}]}],active:{...draft,index:-1}};
const safe=L.sanitizeState(raw,{},bank,types,coverage.retiredQuestionIds);
assert.deepEqual(safe.saved,[q.id]);assert.equal(safe.settings.goal,10);assert.equal(safe.settings.motion,false);assert.equal(safe.attempts[0].answers.length,1);assert.equal(safe.memory[q.id].wrong,1);assert.equal(safe.active,null);assert.deepEqual(safe.orders,{});
assert.doesNotThrow(()=>L.sanitizeState({saved:{},attempts:42,memory:null,settings:[]},{},bank,types));
assert.equal(L.scopeOf([qs[0],qs[1]]).source,'file3');assert.equal(L.scopeOf([qs[0],q]),null);
console.log('PASS audit engine: capped review, adaptive priority, 6 progress groups, actual denominator, malformed-state recovery and draft validation');
