// Optional: npm install --no-save playwright; npx playwright install chromium
// For the Arena sandbox: also install @sparticuz/chromium and set BASIRA_LAMBDA_CHROMIUM=1.
if(process.env.BASIRA_LAMBDA_CHROMIUM==='1')process.env.AWS_EXECUTION_ENV='AWS_Lambda_nodejs22.x';
const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const binary=process.env.BASIRA_LAMBDA_CHROMIUM==='1'?require('@sparticuz/chromium').default:null;const browser=await chromium.launch(binary?{executablePath:await binary.executablePath(),args:binary.args,headless:true}:{headless:true});const page=await browser.newPage({viewport:{width:1440,height:1100}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.BASIRA_PREVIEW_URL||'http://localhost:3000');await page.waitForSelector('.hero');await page.evaluate(()=>document.fonts.ready);assert(await page.evaluate(()=>document.fonts.check('14px "IBM Plex Sans Arabic"')));
for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:950});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow ${width}`)}
await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.floating-card').first().evaluate(el=>getComputedStyle(el).animationName),'none');
await page.setViewportSize({width:390,height:844});
const id=await page.evaluate(()=>questions.find(q=>q.type==='choice').id);
await page.evaluate(id=>startQuiz({ids:[id],count:1}),id);let correct=await page.evaluate(()=>session.options.indexOf(qnow().answer));await page.locator('.option').nth((correct+1)%3).click();await page.locator('#checkBtn').click();await page.waitForSelector('.feedback.wrong');await page.locator('.quiz-actions .btn').first().click();await page.waitForSelector('.score');assert(await page.evaluate(id=>pending().includes(id),id));
await page.reload();await page.waitForSelector('.hero');assert(await page.evaluate(id=>pending().includes(id),id));
for(let round=0;round<2;round++){await page.evaluate(()=>startQuiz({exam:true,count:1,source:'sorular',variant:'modified'}));assert.equal(await page.evaluate(()=>qnow().id),id);const current=await page.evaluate(()=>session.options.indexOf(qnow().answer));assert.notEqual(current,correct);correct=current;await page.locator('.option').nth(current).click();await page.locator('#checkBtn').click();await page.waitForSelector('.score')}
assert.equal(await page.evaluate(()=>pending().length),0);
// Real browser draft/resume and no reshuffle after reload.
await page.evaluate(()=>startQuiz({ids:[questions.find(q=>q.type==='short').id],count:1}));await page.fill('#answerText','إجابتي المحفوظة');await page.getByRole('button',{name:'حفظ وخروج ×'}).click();await page.reload();await page.waitForSelector('.resume');await page.locator('.resume button').click();assert.equal(await page.inputValue('#answerText'),'إجابتي المحفوظة');
await page.getByRole('button',{name:'حفظ وخروج ×'}).click();await page.evaluate(()=>{state.active=null;persist()});
for(const type of ['multiple','order','match','passage_group','hints']){await page.evaluate(type=>{state.active=null;startQuiz({type,count:1,source:'sorular',variant:'modified'})},type);await page.waitForSelector('.quiz-card');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile '+type)}
await page.evaluate(()=>{session=null;state.active=null;render()});await page.setViewportSize({width:1440,height:1100});await page.setViewportSize({width:390,height:844});
await page.evaluate(()=>{session=null;state.active=null;location.hash='#exam';render()});await page.waitForSelector('#examCount');await page.selectOption('#examSource','file3');await page.selectOption('#examVariant','original');await page.selectOption('#examCount','50');await page.locator('#app .btn').first().click();assert.equal(await page.evaluate(()=>session.ids.length),50);assert(await page.evaluate(()=>session.ids.every(id=>byId.get(id).sourceId==='file3'&&byId.get(id).variant==='original')));for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:950});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`quiz overflow ${width}`)}assert.deepEqual(errors,[]);console.log('PASS Chromium: Arabic local fonts, 4 widths, reduced motion, wrong-answer persistence across reload, automatic next-exam recall, shuffled correct positions, mastery, draft resume, complex mobile controls, no runtime errors');await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
