// Mirrors assets/data/types.json; checked by tools/validate_content.py.
const kinds = {
  'choice': 'اختيار من متعدد',
  'single': 'اختيار إجابة واحدة',
  'multiple': 'اختيار عدة إجابات',
  'boolean': 'صح أو خطأ',
  'short': 'اكتب الإجابة',
  'qa': 'سؤال وجواب',
  'definition': 'تعريف ومصطلح',
  'description': 'وصف واستنتاج',
  'hints': 'تلميحات واستنتاج',
  'cause_effect': 'سبب ونتيجة',
  'effect_cause': 'نتيجة وسبب',
  'comparison': 'مقارنة',
  'order': 'ترتيب',
  'match': 'توصيل / مطابقة',
  'passage_question': 'نص وسؤال',
  'read_answer': 'اقرأ وأجب',
  'passage_group': 'عدة أسئلة على نص واحد',
  'correct_statement': 'تحديد العبارة الصحيحة',
  'incorrect_statement': 'تحديد العبارة الخاطئة',
};
const questionModes = {
  'choice': 'single',
  'single': 'single',
  'multiple': 'multi',
  'boolean': 'single',
  'short': 'self',
  'qa': 'self',
  'definition': 'text',
  'description': 'self',
  'hints': 'text',
  'cause_effect': 'self',
  'effect_cause': 'self',
  'comparison': 'self',
  'order': 'order',
  'match': 'match',
  'passage_question': 'self',
  'read_answer': 'self',
  'passage_group': 'group',
  'correct_statement': 'single',
  'incorrect_statement': 'single',
};
