'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],L=Learning;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let questions=[],catalog={},coverage={},byId=new Map(),session=null,listPage=0,listRoute='practice',lastHash='#home';
const KEY='basira-learning-v2',TOPICS=['الطهارة والعبادات','الصلاة','العقيدة'];
let state={schema:2,saved:[],attempts:[],memory:{},orders:{},settings:{large:false,motion:true,focus:false,goal:10},active:null};
let selection={source:'file2',variant:'modified'};
const sources=()=>coverage.sources||[];
const sourceOptions=(value)=>sources().map(x=>`<option value="${x.id}" ${value===x.id?'selected':''}>${esc(x.title)}</option>`).join('');
const reference=q=>`${q.sourceFile} · الأسطر ${Array.isArray(q.evidence)?q.evidence.map(e=>`${e.lineStart}–${e.lineEnd}`).join('، '):`${q.lineStart}–${q.lineEnd}`}`;
const provenance=q=>q.variant==='original'?(q.originalFormat==='notes'?'نص أصلي مطابق — ليس سؤالًا أصليًا':'سؤال أصلي مطابق'):'سؤال معدّل من المصدر';
function chooseCourse(source,variant){selection={source,variant};state.scope=selection;persist();go('practice')}
function scopeControls(prefix){return `<select id="${prefix}Source" aria-label="الملف">${sourceOptions(selection.source)}</select><select id="${prefix}Variant" aria-label="الصياغة"><option value="original" ${selection.variant==='original'?'selected':''}>مطابق للمصدر</option><option value="modified" ${selection.variant==='modified'?'selected':''}>معدّل — تحليل ومقارنة</option></select>`}
function scopeNote(prefix){const source=$('#'+prefix+'Source').value,variant=$('#'+prefix+'Variant').value;selection={source,variant};state.scope=selection;persist();const topic=$('#'+(prefix==='exam'?'examSection':'sectionFilter'));if(topic){const selected=topic.value;topic.innerHTML='<option value="">كل موضوعات الملف</option>'+[...new Set(questions.filter(q=>q.sourceId===source).map(q=>q.section))].map(t=>`<option>${esc(t)}</option>`).join('');topic.value=[...topic.options].some(o=>o.value===selected)?selected:'';}const typeSelect=$('#typeFilter');if(prefix==='list'&&typeSelect){const previous=typeSelect.value;typeSelect.innerHTML='<option value="">كل أنواع التعلّم</option>'+Object.entries(catalog).filter(([k])=>questions.some(q=>!q.reviewOnly&&q.sourceId===source&&q.variant===variant&&q.type===k)).map(([k,v])=>`<option value="${k}">${esc(v.label)}</option>`).join('');typeSelect.value=[...typeSelect.options].some(o=>o.value===previous)?previous:'';}const info=sources().find(s=>s.id===source);const count=questions.filter(q=>!q.reviewOnly&&q.sourceId===source&&q.variant===variant).length;$('#scopeNote').textContent=info.note+' المتاح في هذا النمط: '+count+'؛ إذا طلبت أكثر يُعرض المتاح دون تكرار.';}
const mode=q=>catalog[q.type].mode,selfGraded=q=>mode(q)==='self',qnow=()=>byId.get(session.ids[session.index]);
const pending=()=>L.pending(state.memory).filter(id=>byId.has(id)&&!byId.get(id).reviewOnly);
const persist=()=>{try{localStorage.setItem(KEY,JSON.stringify(state));return true}catch{toast('تعذّر الحفظ المحلي. قد تكون مساحة المتصفح ممتلئة.');return false}};
const today=()=>new Date().toLocaleDateString('en-CA');
const todayCount=()=>Object.values(state.memory).filter(v=>new Date(v.last).toLocaleDateString('en-CA')===today()).length;
const score=()=>{const a=state.attempts.flatMap(x=>x.answers);return a.length?Math.round(a.filter(x=>x.correct).length/a.length*100):0};
function recoveryCopy(){try{const raw=localStorage.getItem(KEY);if(raw&&!localStorage.getItem(KEY+'.recovery'))localStorage.setItem(KEY+'.recovery',raw)}catch{}}
function restore(){
 try{const stored=JSON.parse(localStorage.getItem(KEY)||'null');if(stored?.schema===2)state={...state,...stored,settings:{...state.settings,...stored.settings}};
 else{const previous=JSON.parse(localStorage.getItem('basira-'+coverage.datasetId)||'null');if(previous){state.saved=previous.saved||[];state.attempts=previous.attempts||[];for(const a of state.attempts)for(const x of a.answers)L.record(state.memory,x.id,x.correct,a.date,new Date(a.date).getTime())}}}
 catch{recoveryCopy();toast('تعذّر قراءة بعض بيانات الحفظ. احتفظنا بنسخة إنقاذ محلية إن توفرت مساحة.')}
 if((state.active&&!L.validSession(state.active,byId,catalog))||!Array.isArray(state.saved)||!Array.isArray(state.attempts)||!state.settings||!state.memory)recoveryCopy();
 state=L.sanitizeState(state,{},questions,catalog,coverage.retiredQuestionIds||[]);
 state.saved=state.saved.filter(id=>byId.has(id)&&!byId.get(id).reviewOnly);state.attempts=state.attempts.filter(a=>a.answers?.length&&a.answers.every(x=>(byId.has(x.id)||(coverage.retiredQuestionIds||[]).includes(x.id))&&typeof x.correct==='boolean'));
 for(const id of Object.keys(state.memory))if(!byId.has(Number(id))||byId.get(Number(id)).reviewOnly)delete state.memory[id];
 if(state.active&&!state.active.ids.every(id=>byId.has(id)&&!byId.get(id).reviewOnly))state.active=null;
 if(state.scope&&sources().some(s=>s.id===state.scope.source)&&['original','modified'].includes(state.scope.variant))selection={...state.scope};
 applySettings();persist();
}
function applySettings(){document.body.classList.toggle('large-text',!!state.settings.large);document.body.classList.toggle('reduce-motion',!state.settings.motion);document.body.classList.toggle('focus-mode',!!session&&state.settings.focus)}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3000)}
function save(id){state.saved=state.saved.includes(id)?state.saved.filter(x=>x!==id):[...state.saved,id];const stored=persist();if(stored)toast(state.saved.includes(id)?'حُفظ السؤال في مساحتك':'أُزيل من المحفوظات');if(session)drawQuiz();else if(['saved','practice','review'].includes(listRoute)&&$('#questionList'))filter(false)}
function badge(){const n=pending().length;$('#reviewBadge').textContent=n;$('#streak').textContent=todayCount()?`${todayCount()} أسئلة اليوم ✧`:'بداية جديدة ✧'}
function go(page){location.hash=page; if(location.hash===lastHash)render()}
function heading(title,sub,extra=''){return `<div class="page-top"><div><h1>${title}</h1><p>${sub}</p></div>${extra}</div>`}
function stats(){return `<section class="stats"><div class="stat"><span class="stat-icon">◈</span><div><strong>${questions.filter(q=>!q.reviewOnly).length.toLocaleString('en')}</strong><small>صيغة سؤال تنتظرك</small></div></div><div class="stat"><span class="stat-icon">✓</span><div><strong>${Object.keys(state.memory).length}</strong><small>سؤالًا تدربت عليه</small></div></div><div class="stat"><span class="stat-icon">↺</span><div><strong>${pending().length}</strong><small>فرصة جديدة للتثبيت</small></div></div><div class="stat"><span class="stat-icon">◴</span><div><strong>${score()}<span style="font-size:13px">٪</span></strong><small>دقة جلساتك المكتملة</small></div></div></section>`}
const iconsvg=(name)=>{const paths={book:'M4 4h6c2 0 2 2 2 2s0-2 2-2h6v15h-6c-2 0-2 1-2 1s0-1-2-1H4z M12 6v14',arrow:'M19 12H5m6-6-6 6 6 6',spark:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5z',chart:'M5 19V9m7 10V4m7 15v-7',check:'m5 12 4 4L19 6',review:'M4 11a8 8 0 1 1 2 7M4 4v7h7'};return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name].split(' M').map(p=>`<path d="${p.startsWith('M')||p.startsWith('m')?p:'M'+p}"/>`).join('')}</svg>`};
function home(){const due=pending().length,done=todayCount(),goal=state.settings.goal;
return `<div class="welcome-line"><span><i class="live-dot"></i> مساحة تعلّمك الشخصية</span><span>خطوة صغيرة. أثر مستمر.</span></div>${state.active?`<div class="resume"><div><b>نكمل من حيث توقّفنا؟</b><p>جلستك محفوظة · ${Math.min(state.active.index+1,state.active.ids.length)} / ${state.active.ids.length}</p></div><button class="btn" onclick="resume()">متابعة الجلسة ${iconsvg('arrow')}</button></div>`:''}
<section class="hero"><div class="hero-copy"><span class="eyebrow">بصيرة / مساحة للفهم</span><h1>كل يوم،<br>نسخة <em>أكثر معرفة.</em></h1><p>اختر ما تريد تعلّمه، اختبر فهمك، وامنح كل معلومة<br class="desktop-break"> فرصة لتبقى. مسارك يبدأ من هنا.</p><button class="btn" onclick="go('practice')">ابدأ جلسة تعلّم ${iconsvg('arrow')}</button><div class="hero-caption"><span class="tiny-stack">${iconsvg('book')}</span> ثلاثة أقسام مستقلة. ومعرفة تستحق وقتك.</div></div><article class="challenge-card"><div class="challenge-top"><span>تحدّي المعرفة</span>${iconsvg('spark')}</div><div class="challenge-number">50<span>سؤالًا<br>لفهم أعمق</span></div><p>اختر الملف والصياغة.<br>خذ وقتك، ودع معرفتك تتحدث.</p><button class="btn white" onclick="go('exam')">جهّز اختبارك ${iconsvg('arrow')}</button><div class="challenge-footer"><span>بلا مؤقّت</span><span>على طريقتك</span></div></article></section>
<div class="dashboard-grid"><section class="learning-space"><div class="section-head"><div><span class="eyebrow">أقسام التعلّم، بأسلوب تفاعلي</span><h2>ماذا ستتعلّم اليوم؟</h2></div><span class="count-chip">03 أقسام</span></div><section class="tracks">${sources().map((src,i)=>`<article class="track course-card"><div class="course-emblem emblem-${i}">${iconsvg(i===2?'spark':'book')}</div><div class="course-main"><small>القسم 0${i+1} <span> / ${esc(src.file)}</span></small><h3>${['المراجعة الأساسية','الدروس الهجائية','العقيدة'][i]}</h3><p>${src.format==='notes'?'نصوص أصلية وتدريبات على القراءة والتهجّي.':i===0?'مفاهيم العبادات والصلاة وأصول العقيدة.':'افهم المصطلحات، وقارن المعاني، وثبّت معرفتك.'}</p><div class="course-actions"><button class="btn outline" onclick="chooseCourse('${src.id}','original')">${src.format==='notes'?'نصوص مطابقة':'أسئلة مطابقة'} <b>${src.originalCount}</b></button><button class="btn soft" onclick="chooseCourse('${src.id}','modified')">تدريبات معدّلة <b>${src.modifiedCount}</b> ${iconsvg('arrow')}</button></div>${src.format==='notes'?'<small class="source-honesty">المصدر شرح بلا أسئلة جاهزة؛ المطابق ينقل نصوصه كما هي.</small>':''}</div><span class="course-number">0${i+1}</span></article>`).join('')}</section></section>
<aside class="insight-rail"><section class="goal-card"><div class="section-head"><h3>إيقاعك اليومي</h3>${iconsvg('chart')}</div><div class="goal-ring" style="--progress:${Math.min(done/goal,1)*360}deg"><div><strong>${done}<small> / ${goal}</small></strong><span>تدريبات اليوم</span></div></div><p>${done>=goal?'أحسنت! حققت هدفك اليوم.':'لا تحتاج الكثير. فقط خطوة أخرى.'}</p><button class="text-btn" onclick="settings()">تخصيص هدفي اليومي</button></section><section class="review-panel"><span class="mini-label">مساحة للمحاولة مجددًا</span><h3>${due?'كل خطأ، فرصة.':'ابدأ بثقة.'}</h3><p>${due?`${due} سؤالًا بانتظار فرصة ثانية.`:'أخطاؤك تُحفظ لتعود إليها وتفهمها أكثر.'} المراجعة تبقى داخل الملف والصياغة المختارين.</p><button class="text-btn" onclick="go('review')">فرصتي الثانية ${iconsvg('arrow')}</button></section></aside></div>
<section class="journey-strip"><div>${iconsvg('chart')}<span>رحلتك، بالأرقام</span></div><div><strong>${Object.keys(state.memory).length}</strong><small>سؤالًا تدربت عليه</small></div><div><strong>${score()}٪</strong><small>دقة المحاولات المكتملة</small></div><button class="text-btn" onclick="go('progress')">كل التقدّم ${iconsvg('arrow')}</button></section>`}
function render(){session=null;applySettings();badge();const page=location.hash.slice(1)||'home';lastHash=location.hash||'#home';listRoute=page;const titles={home:'مساحتي',practice:'اكتشف التدريبات',exam:'اختبر معرفتك',review:'فرصتي الثانية',progress:'رحلة تقدّمي',saved:'أسئلتي المحفوظة'};$('#crumb').textContent=titles[page]||titles.home;$$('nav a').forEach(a=>a.classList.toggle('active',a.dataset.page===page));
 if(page==='home'||!titles[page])$('#app').innerHTML=home();
 else if(['practice','saved','review'].includes(page))renderList(page);
 else if(page==='exam')renderExam();else progress();window.scrollTo(0,0);
}
function renderList(page){$('#app').innerHTML=heading({practice:'اكتشف طريقتك في التعلّم',saved:'معلومات تستحق الاحتفاظ',review:'كل خطأ… بداية فهم جديد'}[page],page==='review'?'هذه الأسئلة تعود في اختبار نفس الملف والصياغة، حتى تجيب مرتين بشكل صحيح.':'تدرّب على أفكار المراجعة بطرق متعددة. اختر ما يناسب مزاجك اليوم.',page==='review'&&pending().length?'<button class="btn" onclick="reviewFiltered()">راجع هذا الاختيار (حتى 10) ←</button>':'')+`<div class="filters">${scopeControls('list')}<input type="search" id="search" placeholder="ابحث عن مفهوم أو سؤال…" aria-label="البحث"><select id="sectionFilter" aria-label="المسار"><option value="">كل المسارات</option>${TOPICS.map(t=>`<option>${t}</option>`).join('')}</select><select id="typeFilter" aria-label="نوع السؤال"><option value="">كل أنواع التعلّم</option>${Object.entries(catalog).filter(([k])=>questions.some(q=>q.type===k&&!q.reviewOnly&&q.sourceId===selection.source&&q.variant===selection.variant)).map(([k,v])=>`<option value="${k}">${v.label}</option>`).join('')}</select></div><p class="note" id="scopeNote"></p><div id="listScopes"></div><div id="questionList"></div><div id="pagination"></div>`;['search','sectionFilter','typeFilter','listSource','listVariant'].forEach(id=>$('#'+id).oninput=()=>{if(id==='listSource')$('#sectionFilter').value='';scopeNote('list');filter()});scopeNote('list');filter()}
function filtered(){const due=new Set(pending());return questions.filter(q=>!q.reviewOnly&&q.sourceId===$('#listSource').value&&q.variant===$('#listVariant').value&&(listRoute!=='saved'||state.saved.includes(q.id))&&(listRoute!=='review'||due.has(q.id))&&(!$('#sectionFilter').value||q.section===$('#sectionFilter').value)&&(!$('#typeFilter').value||q.type===$('#typeFilter').value)&&L.normalize(q.prompt).includes(L.normalize($('#search').value)))}
function jumpScope(source,variant){selection={source,variant};state.scope=selection;persist();renderList(listRoute)}
function scopeLinks(){if(!['review','saved'].includes(listRoute))return '';const ids=new Set(listRoute==='review'?pending():state.saved);return `<div class="scope-summary"><p>${ids.size} ${listRoute==='review'?'خطأ معلّق':'سؤال محفوظ'} في جميع الأقسام. اختر مجموعة لعرضها؛ لا نخلط الملفات.</p><div class="scope-links">${sources().flatMap(src=>['original','modified'].map(variant=>{const count=questions.filter(q=>!q.reviewOnly&&ids.has(q.id)&&q.sourceId===src.id&&q.variant===variant).length;return count?`<button class="btn outline" onclick="jumpScope('${src.id}','${variant}')">${esc(src.file)} · ${variant==='original'?'مطابق':'معدّل'} (${count})</button>`:''})).join('')}</div></div>`}
function reviewFiltered(){startQuiz({review:true,ids:filtered().map(q=>q.id),count:10})}
function filter(reset=true){if($('#listScopes'))$('#listScopes').innerHTML=scopeLinks();if(reset)listPage=0;const all=filtered(),pages=Math.max(1,Math.ceil(all.length/16));listPage=Math.min(listPage,pages-1);const list=all.slice(listPage*16,(listPage+1)*16);$('#questionList').innerHTML=`<div class="section-head"><small>${all.length.toLocaleString('en')} صيغة ضمن الاختيار الحالي · الصفحة ${listPage+1} من ${pages}</small>${all.length?'<button class="text-btn" onclick="trainFiltered()">تدرّب على هذا الاختيار ←</button>':''}</div>`+(list.length?list.map(q=>`<article class="question-row"><div class="section-head"><span class="pill">${catalog[q.type].label}</span><small>${esc(q.sourceFile)} · ${provenance(q)} · ${q.section} · ${q.difficulty||'متوسط'} ${pending().includes(q.id)?'· ↺ قيد التثبيت':''}</small></div><p>${esc(q.prompt)}</p><div class="row-actions"><button class="btn outline" onclick="startQuiz({ids:[${q.id}],count:1})">حلّ السؤال ←</button><button class="text-btn" onclick="save(${q.id})">${state.saved.includes(q.id)?'◆ محفوظ':'◇ احفظ لوقت لاحق'}</button>${listRoute==='review'?`<small>إجابات التثبيت ${Math.min(state.memory[q.id]?.streak||0,2)} / 2</small>`:''}</div></article>`).join(''):`<div class="empty"><span>✧</span><h3>${listRoute==='review'?(pending().length?'لا توجد أخطاء ضمن هذا الاختيار. توجد أخطاء في اختيارات أخرى.':'لا توجد أخطاء معلّقة. رائع!'):'لا توجد أسئلة مطابقة الآن.'}</h3><p>غيّر الاختيارات أو ابدأ تجربة تعلّم جديدة.</p><button class="btn" onclick="startQuiz({count:5})">ابدأ تدريبًا قصيرًا ←</button></div>`);$('#pagination').innerHTML=pages>1?`<div class="pagination"><button class="btn outline" ${listPage===0?'disabled':''} onclick="listPage--;filter(false);window.scrollTo(0,0)">السابق</button><span>${listPage+1} / ${pages}</span><button class="btn outline" ${listPage===pages-1?'disabled':''} onclick="listPage++;filter(false);window.scrollTo(0,0)">التالي</button></div>`:''}
function trainFiltered(){const ids=filtered().map(q=>q.id);startQuiz({ids,count:10})}
function renderExam(){$('#app').innerHTML=heading('اختبار على مقاسك','ليس سباقًا مع الوقت. مساحة لتكتشف ما تعرفه، وما يستحق مراجعة أخرى.')+`<div class="exam-workspace"><section class="panel exam-builder"><div class="setup-step"><span>01</span><div><h3>اختر مادّتك وطريقة السؤال</h3><p>ملف واحد، وصياغة واحدة. بلا خلط.</p></div></div><div class="filters">${scopeControls('exam')}</div><div class="setup-step"><span>02</span><div><h3>حدّد مساحة التحدّي</h3><p>اختر الموضوع وعدد الأسئلة المناسب لك.</p></div></div><div class="filters"><select id="examSection" aria-label="مسار الاختبار"><option value="">جميع موضوعات الملف</option></select><select id="examCount" aria-label="عدد الأسئلة">${[5,10,20,50].map(n=>`<option value="${n}" ${n===50?'selected':''}>${n} سؤالًا</option>`).join('')}</select></div><p class="note" id="scopeNote"></p><button class="btn" onclick="startQuiz({exam:true,source:$('#examSource').value,variant:$('#examVariant').value,section:$('#examSection').value,count:Number($('#examCount').value)})">أنا جاهز، لنبدأ ${iconsvg('arrow')}</button></section><aside class="exam-brief"><span class="eyebrow">جلسة جديدة للفهم</span><strong id="summaryCount">50</strong><h3>سؤالًا، على إيقاعك.</h3><div class="brief-rule">${iconsvg('review')}<p>أخطاؤك أولًا، ضمن الملف والصياغة والعدد المختار. وما زاد يبقى محفوظًا.</p></div><div class="brief-rule">${iconsvg('check')}<p>الإجابات المفتوحة تقيّمها ذاتيًا بمقارنتها بالمرجع، لا بمطابقة الكلمات.</p></div><div class="brief-rule">${iconsvg('book')}<p>يمكنك حفظ الجلسة والعودة إليها. لا مؤقّت، ولا استعجال.</p></div></aside></div>`;for(const id of ['examSource','examVariant'])$('#'+id).onchange=()=>{if(id==='examSource')$('#examSection').value='';scopeNote('exam');updateExamCount()};$('#examCount').onchange=updateExamCount;$('#examSection').onchange=updateExamCount;scopeNote('exam');updateExamCount()}
function updateExamCount(){const available=questions.filter(q=>!q.reviewOnly&&q.sourceId===$('#examSource').value&&q.variant===$('#examVariant').value&&(!$('#examSection').value||q.section===$('#examSection').value)).length;const count=Math.min(Number($('#examCount').value),available);$('#summaryCount').textContent=count;const button=$('.exam-builder>.btn');if(button){button.disabled=!count;button.title=count?'':'لا توجد أسئلة في هذا الاختيار';}}
function startQuiz(config={}){
 if(!config.ids){config={source:selection.source,variant:selection.variant,...config}}
 if(state.active&&!session&&!confirm('لديك جلسة غير مكتملة. بدء جلسة جديدة يستبدلها، لكن إجاباتك المسجلة وأخطاءك ستبقى محفوظة.'))return;
 const list=L.plan(questions,state.memory,config);if(list.length&&list.length<(config.count||10)&&!config.review)toast('المتاح لهذا الاختيار '+list.length+' فقط؛ لا نكرر الأسئلة لإكمال العدد.');if(!list.length){toast('لا توجد أسئلة لهذا الاختيار الآن.');return}
 if(list.every(q=>q.sourceId===list[0].sourceId&&q.variant===list[0].variant)){selection={source:list[0].sourceId,variant:list[0].variant};state.scope=selection;}
 session={id:Date.now()+'-'+Math.random().toString(16).slice(2),ids:list.map(q=>q.id),index:0,source:selection.source,variant:selection.variant,section:config.section||'',type:config.type||'',exam:!!config.exam,review:!!config.review,answers:[],selected:null,revealed:false,hints:0,options:[],pairOrder:[],partOrder:[],finished:false};prepare();checkpoint();applySettings();drawQuiz();window.scrollTo(0,0);
}
function prepare(){const q=qnow(),m=mode(q);session.selected=['multi','order','match','group'].includes(m)?[]:'';session.revealed=false;session.hints=0;session.currentRecorded=false;
 const previous=state.orders[q.id]||[];session.options=L.varied(q.options,previous);
 if(m==='single'&&previous.length&&session.options.indexOf(q.answer)===previous.indexOf(q.answer))session.options.push(session.options.shift());
 if(m==='multi'&&previous.length&&session.options.every((v,i)=>q.correct.includes(v)===q.correct.includes(previous[i])))session.options.push(session.options.shift());
 if(['single','multi'].includes(m))state.orders[q.id]=session.options;
 if(m==='order'){session.selected=L.shuffle(q.options);if(L.grade(q,session.selected,m))session.selected.push(session.selected.shift())}
 if(m==='match'){session.selected=q.pairs.map(()=> '');session.options=L.varied(q.pairs.map(p=>p.right),previous);state.orders[q.id]=session.options;session.pairOrder=L.shuffle(q.pairs.map((_,i)=>i))}
 if(m==='group'){session.selected=q.parts.map(()=> '');session.partOrder=L.shuffle(q.parts.map((_,i)=>i))}
}
function checkpoint(){state.active=session?JSON.parse(JSON.stringify(session)):null;const stored=persist();badge();return stored}
function resume(){if(!L.validSession(state.active,byId,catalog)){state.active=null;persist();toast('الجلسة المحفوظة غير صالحة للاستئناف؛ تقدّمك المسجل باقٍ.');return}session=JSON.parse(JSON.stringify(state.active));const scope=L.scopeOf(session.ids.map(id=>byId.get(id)));if(scope){selection=scope;state.scope=scope;}persist();applySettings();if(session.index>=session.ids.length)results();else drawQuiz()}
function ready(){const v=session.selected;return Array.isArray(v)?v.length>0&&v.every(x=>String(x).trim()):String(v).trim().length>0}
function selectOption(i){if(session.revealed)return;const value=session.options[i];if(mode(qnow())==='multi')session.selected=session.selected.includes(value)?session.selected.filter(x=>x!==value):[...session.selected,value];else session.selected=value;checkpoint();drawQuiz()}
function input(value,index=null){if(session.revealed)return;if(index===null)session.selected=value;else session.selected[index]=value;checkpoint();$('#checkBtn').disabled=!ready()}
function moveItem(i,d){if(session.revealed)return;const j=i+d;if(j<0||j>=session.selected.length)return;[session.selected[i],session.selected[j]]=[session.selected[j],session.selected[i]];checkpoint();drawQuiz()}
function control(q){const m=mode(q),disabled=session.revealed?'disabled':'';
 if(m==='single'||m==='multi')return `${m==='multi'?'<p class="note">اختر جميع الإجابات المطلوبة. تُحسب النقطة عند اختيار المجموعة الصحيحة دون إضافات.</p>':''}<div class="options">${session.options.map((o,i)=>`<${m==='multi'?'label':'button'} class="option ${(m==='multi'?session.selected.includes(o):session.selected===o)?'selected':''}" ${m==='single'?`${disabled} onclick="selectOption(${i})" aria-pressed="${session.selected===o}"`:''}>${m==='multi'?`<input type="checkbox" ${session.selected.includes(o)?'checked':''} ${disabled} onchange="selectOption(${i})">`:`<span class="option-index">${['أ','ب','ج','د','هـ','و'][i]||i+1}</span>`}<span>${esc(o)}</span></${m==='multi'?'label':'button'}>`).join('')}</div>`;
 if(m==='order')return `<p class="note">حرّك الأجزاء باستخدام السهمين. البداية من الأعلى.</p>${session.selected.map((o,i)=>`<div class="order-row"><span>${i+1}. ${esc(o)}</span><button class="btn outline" aria-label="تحريك العنصر ${i+1} للأعلى" ${session.revealed||i===0?'disabled':''} onclick="moveItem(${i},-1)">↑</button><button class="btn outline" aria-label="تحريك العنصر ${i+1} للأسفل" ${session.revealed||i===session.selected.length-1?'disabled':''} onclick="moveItem(${i},1)">↓</button></div>`).join('')}`;
 if(m==='match')return session.pairOrder.map(i=>`<label class="match-row"><strong>${esc(q.pairs[i].left)}</strong><select ${disabled} aria-label="مطابقة ${esc(q.pairs[i].left)}" onchange="input(this.value,${i})"><option value="">اختر المعنى المناسب…</option>${session.options.map(o=>`<option value="${esc(o)}" ${session.selected[i]===o?'selected':''}>${esc(o)}</option>`).join('')}</select></label>`).join('');
 if(m==='group')return '<p class="note">نقطة واحدة عند صحة جميع إجابات المجموعة.</p>'+session.partOrder.map(i=>`<label class="group-part"><span>${esc(q.parts[i].prompt)}</span><input ${disabled} value="${esc(session.selected[i])}" oninput="input(this.value,${i})" aria-label="إجابة الجزء ${i+1}"></label>`).join('');
 return `<small>${m==='self'?'اكتب فهمك. التقييم بالمقارنة مع المرجع، وليس تطابق الكلمات.':'اكتب الكلمة المحددة، دون شرح إضافي.'}</small><textarea class="textarea" id="answerText" rows="${m==='self'?4:2}" placeholder="خذ وقتك… واكتب إجابتك هنا" ${disabled} oninput="input(this.value)">${esc(session.selected)}</textarea>`;
}
function drawQuiz(){const q=qnow(),correct=session.revealed&&!selfGraded(q)?L.grade(q,session.selected,mode(q)):null;
 $('#app').innerHTML=`<div class="quiz-layout"><div class="quiz-top"><h2>${session.exam?'اختبار المعرفة':session.review?'فرصتك الثانية':'تدريب على مهل'}</h2><button class="text-btn" onclick="pauseQuiz()">حفظ وخروج ×</button></div><section class="quiz-card"><div class="quiz-meta"><span class="pill">${catalog[q.type].label}</span><small>السؤال ${session.index+1} / ${session.ids.length}</small></div><div class="bar"><i style="width:${session.index/session.ids.length*100}%"></i></div><div class="context">${esc(q.sourceFile)} · ${provenance(q)} · ${q.section} ${pending().includes(q.id)?' · ↺ فرصة ثانية':''}</div>${q.passage?`<div class="passage"><small>اقرأ، ثم استنتج</small><p>${esc(q.passage)}</p></div>`:''}<h2 class="question-prompt">${esc(q.prompt)}</h2>${q.hints?.length?`<div class="hints">${q.hints.slice(0,session.hints).map(h=>`<p class="hint">✧ ${esc(h)}</p>`).join('')}<button class="btn outline" ${session.revealed||session.hints>=q.hints.length?'disabled':''} onclick="session.hints++;checkpoint();drawQuiz()">أحتاج تلميحًا (${session.hints}/${q.hints.length})</button></div>`:''}${control(q)}${session.revealed?`<div class="feedback ${correct===false?'wrong':''}" role="status"><h3>${selfGraded(q)?'قارن عناصر إجابتك بالمقاطع المرجعية؛ لا يلزم نسخها أو مطابقة ألفاظها.':correct?'✓ أحسنت! معلومة أخرى في مكانها.':'↺ لا بأس. الآن لديك فرصة لتثبيتها.'}</h3><span class="full-answer">${esc(q.answer)}</span>${q.explanation&&q.explanation!==q.answer?`<details><summary>فهم أعمق للإجابة</summary><p class="full-answer">${esc(q.explanation)}</p></details>`:''}<small>${esc(reference(q))}</small>${q.warning?`<small>${esc(q.warning)}</small>`:''}</div>`:''}<div class="quiz-actions">${session.revealed?(selfGraded(q)?`<button class="btn" onclick="next(true)">إجابتي توافق المرجع ✓</button><button class="btn outline" onclick="next(false)">أحتاج مراجعة ↺</button>`:`<button class="btn" onclick="next(L.grade(qnow(),session.selected,mode(qnow())))">${session.index===session.ids.length-1?'عرض تقدّمي':'السؤال التالي'} ←</button>`):`<button class="btn" id="checkBtn" ${ready()?'':'disabled'} onclick="check()">${session.exam?'تثبيت والمتابعة':'تحقّق من إجابتي'} ←</button><button class="text-btn" onclick="skipQuestion()">لا أعرف بعد</button>`}<button class="text-btn" onclick="save(${q.id})">${state.saved.includes(q.id)?'◆ محفوظ':'◇ حفظ السؤال'}</button></div></section><div class="quiz-help"><span>◴ خذ وقتك، لا يوجد مؤقّت</span><span>↺ الأخطاء محفوظة تلقائيًا</span><span>✧ المصدر مرجع التقييم</span></div></div>`;$('#crumb').textContent=session.exam?'اختبار المعرفة':'وقت التعلّم';
}
function check(){if(!ready()||session.revealed)return;const q=qnow();if(session.exam)next(selfGraded(q)?null:L.grade(q,session.selected,mode(q)));else{if(!selfGraded(q)){L.record(state.memory,q.id,L.grade(q,session.selected,mode(q)),session.id);session.currentRecorded=true;}session.revealed=true;checkpoint();drawQuiz()}}
function skipQuestion(){session.selected='لم أعرف الإجابة بعد';next(false,true)}
function next(correct,skipped=false){const q=qnow();const a={id:q.id,selected:JSON.parse(JSON.stringify(session.selected)),correct,self:selfGraded(q),hints:session.hints,skipped,committed:correct!==null};session.answers.push(a);if(correct!==null&&!session.currentRecorded)L.record(state.memory,q.id,correct,session.id);session.index++;if(session.index<session.ids.length)prepare();checkpoint();if(session.index>=session.ids.length)results();else drawQuiz();window.scrollTo(0,0)}
function pauseQuiz(){const stored=checkpoint();session=null;applySettings();render();toast(stored?'حفظنا مكانك وإجاباتك. عُد متى أحببت.':'لم يتم الحفظ على الجهاز. جلستك باقية مؤقتًا في هذه الصفحة فقط؛ لا تغلقها قبل توفير مساحة.')}
function assess(index,correct){const a=session.answers[index];if(a.correct!==null)return;a.correct=correct;a.committed=true;L.record(state.memory,a.id,correct,session.id);checkpoint();results()}
const displayAnswer=v=>Array.isArray(v)?v.map((x,i)=>`${i+1}. ${x}`).join(' | '):String(v??'');
function results(){const unanswered=session.answers.findIndex(a=>a.correct===null);if(unanswered>=0){const a=session.answers[unanswered],q=byId.get(a.id);$('#app').innerHTML=`<div class="quiz-layout">${heading('خطوة أخيرة: راجع فهمك','هذه إجابة مفتوحة؛ أنت أقدر على تقييم معناها بعد المقارنة.')}<div class="self-review"><span class="pill">تقييم ذاتي · متبقٍ ${session.answers.filter(x=>x.correct===null).length}</span><h2 class="question-prompt">${esc(q.prompt)}</h2><small>${esc(reference(q))} · ${provenance(q)}</small><br><small>إجابتك</small><p class="full-answer">${esc(displayAnswer(a.selected))}</p><div class="passage"><small>الإجابة المرجعية</small><p>${esc(q.answer)}</p></div><div class="quiz-actions"><button class="btn" onclick="assess(${unanswered},true)">إجابتي توافق المرجع ✓</button><button class="btn outline" onclick="assess(${unanswered},false)">أحتاج مراجعة ↺</button></div></div><button class="text-btn" onclick="pauseQuiz()">أكمل التقييم لاحقًا</button></div>`;return}
 const attempt={id:session.id,date:new Date().toISOString(),exam:session.exam,source:session.source,variant:session.variant,section:session.section||'',answers:session.answers};if(!state.attempts.some(a=>a.id===attempt.id))state.attempts.push(attempt);session=null;state.active=null;persist();applySettings();badge();showResult(attempt)}
function showResult(a){const correct=a.answers.filter(x=>x.correct).length,pct=Math.round(correct/a.answers.length*100);$('#app').innerHTML=`<div class="quiz-layout"><section class="panel result-head"><span class="result-icon">${pct>=80?'✧':'↗'}</span><h1>${pct>=80?'خطوة تستحق الفخر.':'المحاولة نفسها تقدّم.'}</h1><div class="score">${pct}٪</div><p class="muted">ليست مجرد نتيجة. أنت تعرف الآن ما أتقنته، وما ستتعلّمه تاليًا.</p><div class="result-summary"><span>✓ ${correct} إجابات توافق المرجع</span><span>↺ ${a.answers.length-correct} فرص للمراجعة</span></div>${a.answers.some(x=>x.self)?'<small>تشمل النتيجة تقييمك الذاتي للإجابات المفتوحة.</small>':''}<div class="quiz-actions" style="justify-content:center"><button class="btn" onclick="go('progress')">شاهد رحلة تقدّمك ←</button><button class="btn outline" onclick="startQuiz({exam:true,count:5})">اختبار جديد مع أخطائي</button></div></section><div class="note">الأخطاء أصبحت في «فرصتي الثانية» وستعود في اختبار نفس الملف والصياغة ضمن العدد المختار. تخرج من القائمة بعد إجابتين صحيحتين في جلستين مختلفتين.</div>${a.answers.map(x=>{const q=byId.get(x.id);return `<article class="question-row"><span class="pill ${x.correct?'':'amber'}">${x.correct?'✓ توافق المرجع':'↺ أحتاج مراجعة'}</span><p>${esc(q.prompt)}</p><small>إجابتك</small><span class="full-answer">${esc(displayAnswer(x.selected))}</span><details><summary>الإجابة وشرحها</summary><p class="full-answer">${esc(q.answer)}</p>${q.explanation&&q.explanation!==q.answer?`<p class="full-answer muted">${esc(q.explanation)}</p>`:''}</details><button class="text-btn" onclick="save(${q.id})">◇ احفظ السؤال</button></article>`}).join('')}</div>`;window.scrollTo(0,0)}
function progress(){const n=state.attempts.length,known=Object.values(state.memory).filter(x=>x.streak>=2).length;$('#app').innerHTML=heading('أثر محاولاتك، أمام عينيك','التقدّم الحقيقي ليس ألّا تخطئ، بل أن تعود وتفهم.')+stats()+`<div class="tracks">${[['✧','الخطوة الأولى',n>=1,'أكمل جلسة تعلّم واحدة'],['↗','عادة جميلة',n>=5,'أكمل خمس جلسات'],['◈','معرفة تثبت',known>=10,'ثبّت عشرة أسئلة بإجابتين']].map(([icon,title,unlocked,desc])=>`<div class="achievement ${unlocked?'':'locked'}"><span>${icon}</span><div><h3>${title}</h3><small>${unlocked?'إنجاز حققته بالفعل':desc}</small></div></div>`).join('')}</div><div class="lower"><section class="panel"><h2>تقدّمك في الأقسام والصياغات</h2><p class="note">الشريط يقيس الصيغ المثبتة من كامل الاختيار، وليس نسبة معرفتك بالمادة. الأنشطة صيغ تدريب وليست حقائق مستقلة.</p>${L.sourceProgress(questions,state.memory).map(g=>{const src=sources().find(x=>x.id===g.source);return `<div class="source-progress" style="margin-top:23px"><h3>${esc(src?.title||g.source)} · ${g.variant==='original'?'مطابق':'معدّل'}</h3><small>${g.tried} تمت تجربته من ${g.total} · ${g.mastered} مثبت · ${g.pending} يحتاج مراجعة</small><div class="meter" title="نسبة الصيغ المثبتة من كامل هذا الاختيار"><i style="width:${g.total?g.mastered/g.total*100:0}%"></i></div></div>`}).join('')}</section><section class="panel review-panel"><h2>خطوتك التالية واضحة</h2><p>لديك ${pending().length} سؤالًا ينتظر فرصة ثانية، و${known} سؤالًا أجبت عنه مرتين بشكل صحيح.</p><button class="btn outline" onclick="${pending().length?"go('review')":"go('practice')"}">${pending().length?'ثبّت ما تعلّمته':'اكتشف معلومات جديدة'} ←</button></section></div><section class="panel" style="margin-top:24px"><h2>سجل المحاولات</h2>${state.attempts.length?state.attempts.slice(-20).reverse().map(a=>`<div class="timeline-item"><div>${a.exam?'اختبار المعرفة':'تدريب على مهل'}<br><small>${Number.isFinite(Date.parse(a.date))?new Date(a.date).toLocaleString('ar'):'تاريخ غير متاح'} · ${esc(sources().find(s=>s.id===a.source)?.file||'محاولة سابقة')} ${a.variant==='original'?'· مطابق':a.variant==='modified'?'· معدّل':''}</small></div><strong>${a.answers.filter(x=>x.correct).length} / ${a.answers.length}</strong></div>`).join(''):'<div class="empty">أول محاولة ستظهر هنا. ننتظرك بخطوة صغيرة.</div>'}</section>`}
function allModes(){$('#modal').innerHTML=`<div class="modal-overlay"><section class="dialog" role="dialog" aria-modal="true" aria-label="طرق التعلم"><div class="section-head"><h2>طرق مختلفة، ومعرفة واحدة</h2><button class="text-btn" onclick="closeModal()">إغلاق ×</button></div><div class="mode-grid all-modes">${Object.entries(catalog).filter(([k])=>questions.some(q=>q.type===k&&!q.reviewOnly&&q.sourceId===selection.source&&q.variant===selection.variant)).map(([k,v])=>`<button class="mode" onclick="closeModal();startQuiz({type:'${k}',count:5})"><b>${v.label}</b><small>${questions.filter(q=>q.type===k&&!q.reviewOnly&&q.sourceId===selection.source&&q.variant===selection.variant).length} صيغة</small></button>`).join('')}</div></section></div>`;$('#modal button').focus()}
function settings(){$('#modal').innerHTML=`<div class="modal-overlay"><section class="dialog" role="dialog" aria-modal="true" aria-label="إعدادات الراحة"><div class="section-head"><h2>على مقاس راحتك</h2><button class="text-btn" onclick="closeModal()">إغلاق ×</button></div><label class="setting"><span>نص أكبر وأسهل للقراءة</span><input type="checkbox" ${state.settings.large?'checked':''} onchange="state.settings.large=this.checked;applySettings();persist()"></label><label class="setting"><span>حركات هادئة وانتقالات ناعمة</span><input type="checkbox" ${state.settings.motion?'checked':''} onchange="state.settings.motion=this.checked;applySettings();persist()"></label><label class="setting"><span>وضع التركيز أثناء حل الأسئلة</span><input type="checkbox" ${state.settings.focus?'checked':''} onchange="state.settings.focus=this.checked;applySettings();persist()"></label><label class="setting"><span>هدفي اليومي</span><select aria-label="الهدف اليومي" onchange="state.settings.goal=Number(this.value);persist()">${[5,10,15,20].map(n=>`<option value="${n}" ${state.settings.goal===n?'selected':''}>${n} أسئلة</option>`).join('')}</select></label><p class="note">الأنشطة مستمدة من sorular.txt و2.txt و3.txt، وكل ملف قسم مستقل. التصحيح يقيس موافقة المرجع، وليس توثيقًا لصحة أحكامه أو نقوله. يحفظ التطبيق تقدّمك على هذا الجهاز فقط.</p><small>${coverage.trainedUnits} وحدة نصية لها تمارين، و${coverage.criticalUnits} وحدتان محفوظتان خارج التقييم للمراجعة النقدية. لا نختلق محتوى للقوالب الفارغة.</small></section></div>`;$('#modal button').focus()}
function closeModal(){$('#modal').innerHTML='';if(!session&&location.hash!=='#progress'&&$('#app .hero'))render()}
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
window.addEventListener('hashchange',()=>{if(session){checkpoint();session=null}$('#modal').innerHTML='';render()});
window.addEventListener('beforeunload',()=>{if(session)checkpoint()});
Promise.all(['questions','types','coverage'].map(name=>fetch('/assets/data/'+name+'.json').then(r=>{if(!r.ok)throw Error('load');return r.json()}))).then(([q,t,c])=>{questions=q;catalog=t;coverage=c;byId=new Map(q.map(q=>[q.id,q]));restore();render()}).catch(()=>{$('#app').innerHTML='<div class="empty"><h2>تعذّر تحميل التدريبات.</h2><p>تأكد من الاتصال، ثم أعد المحاولة.</p><button class="btn" onclick="location.reload()">إعادة المحاولة</button></div>'});
